name: Test Suite

on:
  push:
    branches: [main]
    paths:
      - "backend/**"

jobs:
  tests:
    name: Smart Contract Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Node.js 21.7.0
        uses: actions/setup-node@v3
        with:
          node-version: 21.7.0

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: "backend/node_modules"
          key: node_modules-${{ hashFiles('backend/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          cd backend
          npm ci

      - name: Run Tests
        run: cd backend && npx hardhat test
